### ISSUE TITLE
Cadastro de usuários: Perfil - Normal

### ISSUE THREAD

**Issue by FredericoSouza12** [tarley/gtm#2]
O Sistema somente permite o cadastro do perfil "Administrador". 

Ao se tentar efetuar cadastro com o perfil "Normal", o sistema apresenta a mensagem de erro abaixo: 

"Ocorreu um erro!
Perfil inválido!"

**Comment by DanielTorres31** [comment]
O backend aceitava somente o perfil administrador. Já foi corrigido.
